# Generated by Django 5.1 on 2024-08-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='datetime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
